version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - "127.0.0.1:53306:3306"
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
